### ISSUE TITLE
http-add-on controller does not works

### ISSUE THREAD

**Issue by tpiperatgod** [kedacore/http-add-on#316]
http-add-on controller does not works

## Expected Behavior
http-add-on controller pod is running

## Actual Behavior
http-add-on controller pod is error

## Steps to Reproduce the Problem

  1. refer to this [doc](https://github.com/kedacore/http-add-on/blob/main/docs/install.md)
  2. install keda
   ```shell
helm repo add kedacore https://kedacore.github.io/charts
helm repo update
NAMESPACE=keda
helm install keda kedacore/keda --namespace ${NAMESPACE} --set watchNamespace=${NAMESPACE} --create-namespace
   ```
  3. install http-add-on
   ```shell
helm install http-add-on kedacore/keda-add-ons-http --namespace ${NAMESPACE}
   ```

## Specifications

- **KEDA Version:** *2.4.0*
- **KEDA HTTP Add-on Version:** *0.2.0*
- **Platform & Version:** *Ubuntu 18.04 LTS x86_64*
- **Kubernetes Version:** *v1.21.5*

**Comment by tpiperatgod** [comment]
the information from command `kubectl get po -oyaml`:

```shell
  containerStatuses:
  - containerID: docker://7fc1177890ce179aa56a22cdd6201a392d3a412d8c56f7b2ae71dd9d825ba5c8
    image: ghcr.io/kedacore/http-add-on-operator:latest
    imageID: docker-pullable://ghcr.io/kedacore/http-add-on-operator@sha256:75f7196f46ad9c252715791457739379366c6312193d9dd4e8f8fb3182722e88
    lastState:
      terminated:
        containerID: docker://7fc1177890ce179aa56a22cdd6201a392d3a412d8c56f7b2ae71dd9d825ba5c8
        exitCode: 1
        finishedAt: "2021-11-10T04:43:47Z"
        reason: Error
        startedAt: "2021-11-10T04:43:47Z"
    name: keda-add-ons-http-operator
    ready: false
    restartCount: 6
    started: false
    state:
      waiting:
        message: back-off 5m0s restarting failed container=keda-add-ons-http-operator
          pod=keda-add-ons-http-controller-manager-b69bd688c-5vhkd_keda(ee35e959-0bdf-49d2-bf53-01df9b351001)
        reason: CrashLoopBackOff
  - containerID: docker://9e61bf6759173cd7c450e16010a5289f363d738b8a7951bd25d7fc7e7e1c20ca
    image: gcr.io/kubebuilder/kube-rbac-proxy:v0.5.0
    imageID: docker-pullable://gcr.io/kubebuilder/kube-rbac-proxy@sha256:e10d1d982dd653db74ca87a1d1ad017bc5ef1aeb651bdea089debf16485b080b
    lastState: {}
    name: kube-rbac-proxy
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2021-11-10T04:37:50Z"
```

and can't any information in logs:
```shell
~# kubectl logs -n keda keda-add-ons-http-controller-manager-b69bd688c-5vhkd keda-add-ons-http-operator -p
~#
```

**Comment by arschles** [comment]
Hi @tpiperatgod I made the mistake of manually pushing images to the registry after aborting a release the other day. Sorry about that! Things should be back to normal now, if you don't mind trying again.

**Comment by tpiperatgod** [comment]
Thx @arschles 

since i have built and replaced the operator and the interceptor image, these two deployments works. i can access the xkcd svc:
```
# curl http://myhost.com
Hello from XKCD-serv! 👋
```
BUT..

the problems are:
1. no change in the number of replicas of xkcd deployments, even use `hey -z 30s -c 50 'http://myhost.com'` to test it(this should work, right?), nor down to 0
2. i referenced [HTTPScaledObject](https://github.com/tpiperatgod/http-add-on/blob/main/docs/ref/v0.2.0/http_scaled_object.md), but i cannot use the field `spec.scaleTargetRef.targetPendingRequests`

the additional information:
- xkcd HTTPScaledObject configuration
```yaml
# kubectl get -n keda httpscaledobjects.http.keda.sh xkcd -oyaml
apiVersion: http.keda.sh/v1alpha1
kind: HTTPScaledObject
metadata:
  annotations:
    meta.helm.sh/release-name: xkcd
    meta.helm.sh/release-namespace: keda
  creationTimestamp: "2021-11-11T05:01:37Z"
  finalizers:
  - httpscaledobject.http.keda.sh
  generation: 2
  labels:
    app.kubernetes.io/managed-by: Helm
  name: xkcd
  namespace: keda
  resourceVersion: "282620"
  uid: c40159ae-a226-4223-9f96-9c8f0e07140b
spec:
  host: myhost.com
  replicas:
    max: 10
  scaleTargetRef:
    deployment: xkcd
    port: 8080
    service: xkcd
status:
  conditions:
  - message: Identified HTTPScaledObject creation signal
    reason: PendingCreation
    status: Unknown
    timestamp: "2021-11-11T05:01:37Z"
    type: Pending
  - message: App ScaledObject created
    reason: AppScaledObjectCreated
    status: "True"
    timestamp: "2021-11-11T05:01:37Z"
    type: Created
  - message: Finished object creation
    reason: HTTPScaledObjectIsReady
    status: "True"
    timestamp: "2021-11-11T05:01:37Z"
    type: Ready
  - message: Identified HTTPScaledObject creation signal
    reason: PendingCreation
    status: Unknown
    timestamp: "2021-11-11T05:01:37Z"
    type: Pending
  - message: App ScaledObject created
    reason: AppScaledObjectCreated
    status: "True"
    timestamp: "2021-11-11T05:01:37Z"
    type: Created
  - message: Finished object creation
    reason: HTTPScaledObjectIsReady
    status: "True"
    timestamp: "2021-11-11T05:01:38Z"
    type: Ready
```
- addon-http-interceptor logs
```shell
# kubectl logs -f -n keda keda-add-ons-http-interceptor-677487574b-5wpgg keda-add-ons-http-interceptor
{"level":"info","ts":1636606039.9589255,"caller":"interceptor/main.go:71","msg":"Interceptor starting"}
{"level":"info","ts":1636606039.9591153,"caller":"interceptor/main.go:76","msg":"Fetching initial routing table"}
{"level":"info","ts":1636606039.9635677,"caller":"interceptor/main.go:149","msg":"starting the proxy server","port":8080}
{"level":"info","ts":1636606039.9636586,"logger":"runProxyServer","caller":"interceptor/main.go:244","msg":"proxy server starting","address":"0.0.0.0:8080"}
{"level":"info","ts":1636606039.9639966,"caller":"interceptor/main.go:125","msg":"starting the admin server","port":9090}
{"level":"info","ts":1636606039.9641426,"logger":"runAdminServer.pkg.queue.AddCountsRoute","caller":"queue/queue_rpc.go:19","msg":"adding queue counts route","path":"/queue"}
{"level":"info","ts":1636606039.9641771,"logger":"runAdminServer.pkg.routing.AddFetchRoute","caller":"routing/table_rpc.go:25","msg":"adding routing ping route","path":"/routing_ping"}
{"level":"info","ts":1636606039.9642737,"logger":"runAdminServer.pkg.routing.AddPingRoute","caller":"routing/table_rpc.go:41","msg":"adding interceptor routing ping route","path":"/routing_ping"}
{"level":"info","ts":1636606039.964414,"logger":"runAdminServer","caller":"interceptor/main.go:215","msg":"admin server starting","address":"0.0.0.0:9090"}
```

**Comment by tpiperatgod** [comment]
> I'm not sure if you built these yourself, or used the ones from ghcr.io that I pushed. regardless, to confirm, have you completely re-installed everything from the helm chart? if not, can you do that?

I cleaned up the environment and reinstalled keda(and http-addon) with the following command:

```shell
helm repo add kedacore https://kedacore.github.io/charts
helm repo update
kubectl create namespace keda
helm install keda kedacore/keda --namespace keda
helm install http-add-on kedacore/keda-add-ons-http --namespace keda
```

The status is as follows:
```shell
# helm list -n keda
NAME       	NAMESPACE	REVISION	UPDATED                                	STATUS  	CHART                  	APP VERSION
http-add-on	keda     	1       	2021-11-12 10:32:36.467128586 +0800 CST	deployed	keda-add-ons-http-0.2.0	0.2.0
keda       	keda     	1       	2021-11-12 10:32:31.378006707 +0800 CST	deployed	keda-2.4.0             	2.4.0

# kubectl get po -n keda
NAME                                                    READY   STATUS             RESTARTS   AGE
keda-add-ons-http-controller-manager-76b9d5b57b-59kw6   1/2     CrashLoopBackOff   5          3m51s
keda-add-ons-http-external-scaler-6b97695b5d-ztqkt      1/1     Running            0          3m51s
keda-add-ons-http-interceptor-6d4c9bc7c4-fjgwl          0/1     CrashLoopBackOff   5          3m51s
keda-operator-5c569bb794-xwnlb                          1/1     Running            0          3m56s
keda-operator-metrics-apiserver-78f4f687dd-z5c42        1/1     Running            0          3m56s

# kubectl get deployments.apps -n keda keda-add-ons-http-controller-manager -o=jsonpath='{.spec.template.spec.containers[1].image}'
ghcr.io/kedacore/http-add-on-operator:latest

# kubectl get deployments.apps -n keda keda-add-ons-http-interceptor -o=jsonpath='{.spec.template.spec.containers[0].image}'
ghcr.io/kedacore/http-add-on-interceptor:latest

# kubectl get deployments.apps -n keda keda-add-ons-http-external-scaler -o=jsonpath='{.spec.template.spec.containers[0].image}'
ghcr.io/kedacore/http-add-on-scaler:latest

# docker image ls|grep keda
ghcr.io/kedacore/http-add-on-operator           latest        b46817d83423   30 hours ago    46.4MB
ghcr.io/kedacore/http-add-on-scaler             latest        26aa34c0b77a   30 hours ago    44.5MB
ghcr.io/kedacore/http-add-on-interceptor        latest        27512c0642db   30 hours ago    41.9MB
ghcr.io/kedacore/keda-metrics-apiserver         2.4.0         c311fb6c4ea8   3 months ago    96.5MB
ghcr.io/kedacore/keda                           2.4.0         3e08f92f2f84   3 months ago    84.2MB
```

The logs of error pods:
```shell
# kubectl logs -f keda-add-ons-http-controller-manager-76b9d5b57b-59kw6 -n keda keda-add-ons-http-operator
flag provided but not defined: -admin-port
Usage of /operator:
  -enable-leader-election
    	Enable leader election for controller manager. Enabling this will ensure there is only one active controller manager.
  -kubeconfig string
    	Paths to a kubeconfig. Only required if out-of-cluster.
  -metrics-addr string
    	The address the metric endpoint binds to. (default ":8080")
    	
# kubectl logs -f keda-add-ons-http-interceptor-6d4c9bc7c4-fjgwl -n keda keda-add-ons-http-interceptor
panic: required key KEDA_HTTP_APP_SERVICE_NAME missing value

goroutine 1 [running]:
github.com/kelseyhightower/envconfig.MustProcess(...)
	/go/pkg/mod/github.com/kelseyhightower/envconfig@v1.4.0/envconfig.go:233
github.com/kedacore/http-add-on/interceptor/config.MustParseOrigin(0xc000049740)
	/go/src/github.com/kedahttp/http-add-on/interceptor/config/origin.go:36 +0x97
main.main()
	/go/src/github.com/kedahttp/http-add-on/interceptor/main.go:28 +0x45
```

Then I built container images(operator, scaler, interceptor) based on the main branch.(on ubuntu 18.04 lts x86_64)
```shell
git clone https://github.com/kedacore/http-add-on.git
cd http-add-on
export KEDAHTTP_OPERATOR_IMAGE='***/http-add-on-operator:latest'
export KEDAHTTP_SCALER_IMAGE='***/http-add-on-scaler:latest'
export KEDAHTTP_INTERCEPTOR_IMAGE='***/http-add-on-interceptor:latest'
mage dockerBuild
```

```shell
# docker image ls|grep keda
***/keda-http-addon-operator                    latest        000a86376580   23 hours ago     48.4MB
***/keda-http-addon-interceptor                 latest        59942974135b   23 hours ago     43.4MB
***/keda-http-addon-scaler                      latest        0a6c2bafcd94   25 hours ago     45.7MB
ghcr.io/kedacore/http-add-on-operator           latest        b46817d83423   30 hours ago     46.4MB
ghcr.io/kedacore/http-add-on-scaler             latest        26aa34c0b77a   30 hours ago     44.5MB
ghcr.io/kedacore/http-add-on-interceptor        latest        27512c0642db   30 hours ago     41.9MB
```

I replaced the ghcr.io image with the one I built and the http-add-on works.
```shell
# kubectl get po -n keda
NAME                                                    READY   STATUS    RESTARTS   AGE
keda-add-ons-http-controller-manager-657fff6f49-8ntn7   2/2     Running   0          16s
keda-add-ons-http-external-scaler-74fbcb959-j65z4       1/1     Running   0          9s
keda-add-ons-http-interceptor-75f95798dc-7tmrd          1/1     Running   0          13s
keda-operator-5c569bb794-xwnlb                          1/1     Running   0          34m
keda-operator-metrics-apiserver-78f4f687dd-z5c42        1/1     Running   0          34m
```

This time I can observe that the xkcd pod follows the http request for scaling.
```shell
# curl myhost.com
error on backend (context marked done while waiting for deployment xkcd to reach > 0 replicas (context deadline exceeded))
# curl myhost.com
error on backend (context marked done while waiting for deployment xkcd to reach > 0 replicas (context deadline exceeded))
# curl myhost.com
Hello from XKCD-serv! 👋

# kubectl get po -n keda -w
NAME                                                    READY   STATUS              RESTARTS   AGE
xkcd-84459f7fbf-d4nm8                                   0/1     Pending             0          0s
xkcd-84459f7fbf-d4nm8                                   0/1     Pending             0          0s
xkcd-84459f7fbf-d4nm8                                   0/1     ContainerCreating   0          0s
xkcd-84459f7fbf-d4nm8                                   0/1     ContainerCreating   0          2s
xkcd-84459f7fbf-d4nm8                                   0/1     Running             0          5s
xkcd-84459f7fbf-d4nm8                                   1/1     Running             0          10s
```

> this can be due to the operator failing to communicate with the external scaler. can you show the operator and external scaler logs?

I can observe that by http traffic size, the number of xkcd's pods scale to 1 and then down to 0, but not greater than 1.

logs of external scaler:
```shell
# kubectl logs -f -n keda  keda-add-ons-http-external-scaler-7f4bfc7-8q22g keda-add-ons-http-external-scaler
{"level":"info","ts":1636696129.794009,"caller":"scaler/main.go:129","msg":"starting grpc server","address":"0.0.0.0:9090"}
{"level":"info","ts":1636696129.7944334,"logger":"startHealthcheckServer","caller":"scaler/main.go:200","msg":"starting health check server","addr":"0.0.0.0:9091"}
```

logs of operator:
```shell
# kubectl logs -f -n keda keda-add-ons-http-controller-manager-744c57fbdd-5d2nj keda-add-ons-http-operator
2021-11-12T06:01:50.030Z	INFO	controller-runtime.metrics	metrics server is starting to listen	{"addr": "127.0.0.1:8080"}
2021-11-12T06:01:50.030Z	INFO	setup.pkg.routing.AddFetchRoute	adding routing ping route	{"path": "/routing_ping"}
2021-11-12T06:01:50.030Z	INFO	starting admin RPC server	{"port": 9090}
2021-11-12T06:01:50.030Z	INFO	setup	starting manager
I1112 06:01:50.031328       1 leaderelection.go:248] attempting to acquire leader lease keda/f8508ff1.keda.sh...
2021-11-12T06:01:50.036Z	INFO	starting metrics server	{"path": "/metrics"}
I1112 06:02:05.186753       1 leaderelection.go:258] successfully acquired lease keda/f8508ff1.keda.sh
2021-11-12T06:02:05.189Z	INFO	controller.httpscaledobject	Starting EventSource	{"reconciler group": "http.keda.sh", "reconciler kind": "HTTPScaledObject", "source": "kind source: /, Kind="}
2021-11-12T06:02:05.189Z	INFO	controller.httpscaledobject	Starting Controller	{"reconciler group": "http.keda.sh", "reconciler kind": "HTTPScaledObject"}
2021-11-12T06:02:05.192Z	DEBUG	events	Normal	{"object": {"kind":"ConfigMap","namespace":"keda","name":"f8508ff1.keda.sh","uid":"2f03637e-5ed5-44f0-8384-68dbe2fa3679","apiVersion":"v1","resourceVersion":"724775"}, "reason": "LeaderElection", "message": "keda-add-ons-http-controller-manager-744c57fbdd-5d2nj_64f50653-b762-4bf9-96ee-4777d822364a became leader"}
2021-11-12T06:02:05.192Z	DEBUG	events	Normal	{"object": {"kind":"Lease","namespace":"keda","name":"f8508ff1.keda.sh","uid":"1d7ddf69-0d36-4d80-a3de-82dce2b0d121","apiVersion":"coordination.k8s.io/v1","resourceVersion":"724776"}, "reason": "LeaderElection", "message": "keda-add-ons-http-controller-manager-744c57fbdd-5d2nj_64f50653-b762-4bf9-96ee-4777d822364a became leader"}
2021-11-12T06:02:05.291Z	INFO	controller.httpscaledobject	Starting workers	{"reconciler group": "http.keda.sh", "reconciler kind": "HTTPScaledObject", "worker count": 1}
2021-11-12T06:02:05.291Z	INFO	controllers.HTTPScaledObject	Reconciliation start	{"HTTPScaledObject.Namespace": "keda", "HTTPScaledObject.Name": "xkcd"}
2021-11-12T06:02:05.292Z	INFO	controllers.HTTPScaledObject	Reconciling HTTPScaledObject	{"HTTPScaledObject.Namespace": "keda", "HTTPScaledObject.Name": "xkcd", "Namespace": "keda", "DeploymentName": "xkcd"}
2021-11-12T06:02:05.293Z	INFO	controllers.HTTPScaledObject	Creating scaled objects	{"reconciler.appObjects": "addObjects", "HTTPScaledObject.name": "xkcd", "HTTPScaledObject.namespace": "keda", "external scaler host name": "keda-add-ons-http-external-scaler.keda.svc.cluster.local:9090"}
2021-11-12T06:02:05.294Z	INFO	controllers.HTTPScaledObject	Creating App ScaledObject	{"reconciler.appObjects": "addObjects", "HTTPScaledObject.name": "xkcd", "HTTPScaledObject.namespace": "keda", "ScaledObject": {"Object":{"apiVersion":"keda.sh/v1alpha1","kind":"ScaledObject","metadata":{"labels":{"app":"kedahttp-xkcd-app","name":"xkcd-app"},"name":"xkcd-app","namespace":"keda"},"spec":{"maxReplicaCount":10,"minReplicaCount":0,"pollingInterval":1,"scaleTargetRef":{"kind":"Deployment","name":"xkcd"},"triggers":[{"metadata":{"host":"myhost.com","scalerAddress":"keda-add-ons-http-external-scaler.keda.svc.cluster.local:9090"},"type":"external-push"}]}}}}
2021-11-12T06:02:05.310Z	INFO	controllers.HTTPScaledObject	User app scaled object already exists, moving on	{"reconciler.appObjects": "addObjects", "HTTPScaledObject.name": "xkcd", "HTTPScaledObject.namespace": "keda"}
2021-11-12T06:02:05.418Z	INFO	controllers.HTTPScaledObject	Updating status on HTTPScaledObject	{"HTTPScaledObject.Namespace": "keda", "HTTPScaledObject.Name": "xkcd", "resource version": "721982"}
2021-11-12T06:02:05.428Z	INFO	controllers.HTTPScaledObject	Updated status on HTTPScaledObject	{"HTTPScaledObject.Namespace": "keda", "HTTPScaledObject.Name": "xkcd", "resource version": "724783"}
2021-11-12T06:02:05.429Z	INFO	controllers.HTTPScaledObject	Updating status on HTTPScaledObject	{"HTTPScaledObject.Namespace": "keda", "HTTPScaledObject.Name": "xkcd", "resource version": "724783"}
2021-11-12T06:02:05.437Z	INFO	controllers.HTTPScaledObject	Updated status on HTTPScaledObject	{"HTTPScaledObject.Namespace": "keda", "HTTPScaledObject.Name": "xkcd", "resource version": "724784"}
2021-11-12T06:02:05.437Z	INFO	controllers.HTTPScaledObject	Reconcile success	{"HTTPScaledObject.Namespace": "keda", "HTTPScaledObject.Name": "xkcd"}
```

logs of interceptor:
```shell
# kubectl logs -f -n keda keda-add-ons-http-interceptor-5596895cfc-q5gks keda-add-ons-http-interceptor
{"level":"info","ts":1636697162.851597,"caller":"interceptor/main.go:71","msg":"Interceptor starting"}
{"level":"info","ts":1636697162.8517601,"caller":"interceptor/main.go:76","msg":"Fetching initial routing table"}
{"level":"info","ts":1636697162.8576298,"caller":"interceptor/main.go:149","msg":"starting the proxy server","port":8080}
{"level":"info","ts":1636697162.8577144,"logger":"runProxyServer","caller":"interceptor/main.go:244","msg":"proxy server starting","address":"0.0.0.0:8080"}
{"level":"info","ts":1636697162.8590472,"caller":"interceptor/main.go:125","msg":"starting the admin server","port":9090}
{"level":"info","ts":1636697162.8592334,"logger":"runAdminServer.pkg.queue.AddCountsRoute","caller":"queue/queue_rpc.go:19","msg":"adding queue counts route","path":"/queue"}
{"level":"info","ts":1636697162.8592649,"logger":"runAdminServer.pkg.routing.AddFetchRoute","caller":"routing/table_rpc.go:25","msg":"adding routing ping route","path":"/routing_ping"}
{"level":"info","ts":1636697162.8593113,"logger":"runAdminServer.pkg.routing.AddPingRoute","caller":"routing/table_rpc.go:41","msg":"adding interceptor routing ping route","path":"/routing_ping"}
{"level":"info","ts":1636697162.859338,"logger":"runAdminServer","caller":"interceptor/main.go:215","msg":"admin server starting","address":"0.0.0.0:9090"}
{"level":"error","ts":1636697178.7194166,"logger":"runProxyServer","caller":"interceptor/proxy_handlers.go:77","msg":"wait function failed, not forwarding request","error":"context marked done while waiting for deployment xkcd to reach > 0 replicas (context deadline exceeded)","stacktrace":"main.newForwardingHandler.func1\n\t/go/src/github.com/kedacore/http-add-on/interceptor/proxy_handlers.go:77\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2049\nmain.countMiddleware.func1\n\t/go/src/github.com/kedacore/http-add-on/interceptor/middleware.go:48\nnet/http.HandlerFunc.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2049\nnet/http.serverHandler.ServeHTTP\n\t/usr/local/go/src/net/http/server.go:2867\nnet/http.(*conn).serve\n\t/usr/local/go/src/net/http/server.go:1932"}
```

> that field won't be enabled until version 0.2.0 is officially released. are you using 0.2.0 builds?

After referring to the [HTTPScaledObjectSpec](https://github.com/kedacore/http-add-on/blob/main/operator/api/v1alpha1/httpscaledobject_types.go#L102) I found that this field should be `spec.targetPendingRequests`.. now i can apply this field.

Maybe there is a writing error here: [docs](https://github.com/kedacore/http-add-on/blob/main/docs/ref/v0.2.0/http_scaled_object.md#the-httpscaledobject)

**Comment by tpiperatgod** [comment]
Since I removed the xkcd hso and reinstalled it, the xkcd pods could be scaled to a number greater than 1.

It seems that I finally experienced the power of keda-http-addon properly:joy:

But there is still a question, after I updated the HSO, the corresponding SO seems to be unchanged. I will try to find the answer from the code and I would be grateful if you could give some guidance, thx!

```shell
# kubectl get httpscaledobjects.http.keda.sh -n keda
NAME   SCALETARGETDEPLOYMENTNAME   SCALETARGETSERVICENAME                               SCALETARGETPORT   MINREPLICAS   MAXREPLICAS   AGE     ACTIVE
xkcd                               {"deployment":"xkcd","port":8080,"service":"xkcd"}                     5             10            5m54s

# kubectl get scaledobjects.keda.sh -n keda
NAME                            SCALETARGETKIND      SCALETARGETNAME                 MIN   MAX   TRIGGERS        AUTHENTICATION   READY   ACTIVE   FALLBACK   AGE
keda-add-ons-http-interceptor   apps/v1.Deployment   keda-add-ons-http-interceptor   1     50    external                         True    True     False      3h13m
xkcd-app                        apps/v1.Deployment   xkcd                            0     10    external-push                    True    False    False      8m29s
```

**Comment by tpiperatgod** [comment]
And do you think it is necessary to check these two images?

```shell
# docker image ls|grep keda
ghcr.io/kedacore/http-add-on-operator           latest        b46817d83423   30 hours ago    46.4MB
ghcr.io/kedacore/http-add-on-interceptor        latest        27512c0642db   30 hours ago    41.9MB
```

**Comment by arschles** [comment]
@tpiperatgod thanks for the very thorough investigation and response! it looks like you still might have the helm chart for `v0.2.0`. I'll look into why that is the latest, but I think I forgot to roll it back. Apologies for that!

I am planning on releasing `v0.2.0` early next week, so this issue would be fixed at that point. It looks like when you built the images yourself, you ran essentially the `v0.2.0` images and things worked better.

Also, when you saw the `error on backend (context marked done while waiting for deployment xkcd to reach > 0 replicas (context deadline exceeded))` error message, that was because of a timeout. Can you try setting the `KEDA_CONDITION_WAIT_TIMEOUT` environment variable to something higher? Try `20s`. In the helm chart, that would be the `--set interceptor.replicas.waitTimeout=20s` flag.

Regarding the `spec.targetPendingRequests` flag, you are right - in `v0.2.0` that field will be available, so I'm glad you were able to access it after you ran the images you built yourself. Right now, the helm chart is at `v0.2.0` but the images are not. Again, big apologies for that. I am working on building better tooling going forward to ensure releases don't break in this way again.

> after I updated the HSO, the corresponding SO seems to be unchanged

can you share the YAML before and after you upgraded? The logic to look at almost certainly starts in the [`Reconcile` method](https://github.com/kedacore/http-add-on/blob/dda17c5eaec7179ea5849d9e3b1d626f3dbc7849/operator/controllers/httpscaledobject_controller.go#L58). My guess is that the field(s) you changed are not getting recognized in the operator as a change. Feel free to file an issue with the HSO before and after YAML.

>And do you think it is necessary to check these two images?

Yes and no. Those images correspond to the `v0.1.0` release, but the latest helm chart still corresponds to the `v0.2.0` release because I forgot to roll them back. For now, I will build images in my personal DockerHub repository with the `v0.2.0-RC1` tag so that you don't have to build your own images. They will be pushed shortly.

The complete helm install command (including the adjusted timeout) would be this:

```shell
helm install http-add-on kedacore/keda-add-ons-http -n ${NAMESPACE} --set images.tag=v0.2.0-RC1 --set interceptor.replicas.waitTimeout=20s --set images.tag=v0.2.0-RC1 --set images.operator=arschles/http-addon-operator --set images.interceptor=arschles/http-addon-interceptor --set images.scaler=arschles/http-addon-scaler
```

Thank you for working with me as I fix my mistakes! 😄

**Comment by arschles** [comment]
Those custom-built images are pushed now. Here they are if you want to look at them:

- [operator](https://hub.docker.com/r/arschles/http-addon-operator/tags)
- [scaler](https://hub.docker.com/r/arschles/http-addon-scaler/tags)
- [interceptor](https://hub.docker.com/r/arschles/http-addon-interceptor/tags)

**Comment by tpiperatgod** [comment]
The command worked.:thumbsup: thx @arschles 
```
helm install http-add-on kedacore/keda-add-ons-http -n ${NAMESPACE} --set interceptor.replicas.waitTimeout=20s --set images.tag=v0.2.0.RC1 --set images.operator=arschles/http-addon-operator --set images.interceptor=arschles/http-addon-interceptor --set images.scaler=arschles/http-addon-scaler
```

**Comment by arschles** [comment]
@tpiperatgod thanks! I'll update the defaults in the chart for that `waitTimeout`
